# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e7a0106ed377cdd314e955b80d4b1a88390acdd4cf630d13b7b6e8f74347797b892a10dbd1587270e102a0d0aa8b6a6077b4ef8e6cace9662b1aa1aaccc9d89

test:
  secret_key_base: b30789ea4e8a24de897d15ac7ced2f5bc324fb6041c2aeda591e0f4f09f16286c6c9b4284b31a15d420707ebe946c80560ec30e6764146a72851821e40dbaccc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
